class RequestType
{
  static const Duration timeOut = Duration(milliseconds: 55000);
  static String? baseUrl;
  static String? attachmentsUrl;
  static String? profileUrl;
  static String? fileUrl;
  static String? fileName = '/files/';
  static String? requestUrl;
  static String? requestName = '/files/RequestDocument/';
  static String? profilePicture = '/files/Profile/';
  static String documentNames = '/files/AnnouncementDocument/';
  static const String privacyPolicy = 'https://www.peopleqlik.com/privacy-policy/';
  static const String termsOfUse = 'https://www.peopleqlik.com/terms-of-service/';

  //static const String testingUrl = 'https://app.peopleqlik.com/ServiceApiV1';
  static const String firstUrl = 'https://bilytica.peopleqlik.com/ServiceApiV1/api/Mobile/Authentications/GetCustomerURL';
  static const String cookieCall = '/api/Authorization/Authentication/Intialize';
  //static const String firstUrl = 'https://bilytica.peopleqlik.com/ServiceApiV1/api/Mobile/Authentications/GetCustomerURL';
  static const String loginUrl = '/api/Mobile/Authentications/UserAuthentication';
  static const String timeOff = '/api/Mobile/LeavesApplication/GetLeaveList';
  static const String getLeaveFormDataUrl = '/api/Mobile/LeavesApplication/GetLeaveApplicationData';
  static const String getLeaveBalanceUrl = '/api/Mobile/LeavesType/GetLeaveTypeDetail';
  static const String getLeaveSummaryUrl= '/api/Mobile/LeavesBalance/GetLeaveSummary';
  static const String getNotificationsUrl = '/api/Mobile/Notifications/GetNotification';
  static const String applyLeaveUrl = '/api/Mobile/LeavesApplication/AddOrUpdate';
  static const String requestNameUrl = '/api/Mobile/Requests/GetRequestInfo';
  static const String getRequestList = '/api/Mobile/Requests/GetRequestList';
  static const String getRequestForm = '/api/Mobile/Requests/GetRequestForm';
  static const String getSpecialRequestForm = '/api/Mobile/Requests/GetLeaveEncashmentRequestForm';
  static const String getSpecialRequestBalance = '/api/Mobile/Requests/GetLeaveEncashmentRequestBalance';
  static const String saveRequest = '/api/Mobile/Requests/Add';
  static const String getApprovals = '/api/Mobile/Approvals/GetApprovalList';
  static const String getPayslip = '/api/Mobile/Payrolls/GetEmployeeSalary';
  static const String getPayListSlip = '/api/Mobile/Payrolls/GetPayslipList';
  static const String settingsApi = '/api/Mobile/Commons/Setting';
  static const String uploadLeaveFile = '/api/Mobile/FilesUpload/LeaveApplicationFiles';
  static const String uploadRequestFile = '/api/Mobile/FilesUpload/RequestDocumentFiles';
  static const String uploadRequestSpecialFile = '/api/Mobile/FilesUpload/LeaveEncashmentFiles';
  static const String getAnnouncementList = '/api/Mobile/Announcements/GetAnnouncement';
  static const String getAnnouncementDetail = '/api/Mobile/Announcements/GetAnnouncementDetail';
  static const String getApprovalsDetails = '/api/Mobile/Approvals/GetLeaveApplicationDetail';
  static const String postApprovalsAcceptReject = '/api/ESS/Approval/ApplicationApprovalWeb';
  static const String saveAttendance = '/api/Mobile/Attendances/AddAttendance';
  static const String getDashboard = '/api/Mobile/Commons/DashboardV1';
  static const String updateLanguage = '/api/Mobile/Commons/UpdateUserCulture';
  static const String requestDetailUrl = '/api/Mobile/Requests/GetRequestByCode';
  static const String getLeaveDetailUrl = '/api/Mobile/LeavesApplication/GetLeaveByApplicationCodeV1';
  static const String getSpecialRequestList = '/api/Mobile/Requests/GetLeaveEncashmentRequestList';
  static const String saveSpecialRequest = '/api/Mobile/Requests/AddLeaveEncashmentRequest';
  static const String getSeparationRequestApi = '/api/Mobile/Requests/GetLeafLevelEmployeesForSeparationRequest';
  static const String saveSeparationRequest = '/api/Mobile/Requests/AddSeparationRequest';
  static const String getSeparationRequestList = '/api/Mobile/Requests/GetEmployeeSeparationRequestList';
  static const String getSeparationRequestDetailApi = '/api/Mobile/Requests/GetSeparationRequestById';
  static const String getEncashmentRequestDetailApi = '/api/Mobile/Requests/LeaveEncashmentReqDetail';
  static const String saveSeparationCalendar = '/api/Mobile/Requests/UpdateLastWorkingDate';
  static const String teamApi = '/api/Mobile/Requests/GetLeafLevelEmployeesForAttendance';
  static const String holidays = '/api/Mobile/Requests/GetHolidays';
  static const String getTimeSheet = '/api/Mobile/Requests/GetWeeklyAttendance';
  static const String cancelTimeOff = '/api/Mobile/LeavesApplication/CancelEmployeeLeave';
  static const String timeRegulation = '/api/Mobile/Requests/GetMissingAttendanceRequestList';
  static const String dateSelectMovementSlip = '/api/Mobile/Requests/GetOfficePermisionNew';
  static const String submitMovementSlip = '/api/Mobile/Requests/AddWaiveOffRequest';
  static const String getMonthlyTimeRegulationListApi = '/api/Mobile/Requests/GetMonthlyAttendance';
  static const String getTimeRegulationDetails = '/api/Mobile/Requests/TimeRegularizationReqDetail';
  static const String getMyTeamOvertime = '/api/Mobile/Requests/GetMyTeamOvertime';
  static const String getEmployeeOverTime = '/api/Mobile/Requests/GetleafLevelEmloyeeForOvertime';
  static const String overtimeTimeRange = '/api/Mobile/Requests/GetShiftRangeForOvertime';
  static const String overtimeApply = '/api/Mobile/Requests/AddOvertime';
  static const String getOvertimeList = '/api/Mobile/Requests/GetOvertimeRequests';
  static const String getOverTimeDetail = '/api/Mobile/Requests/GetOvertimeRequestDetailV1';
  static const String submitShiftApi = '/api/Mobile/Requests/AddDefaultShift';
  static const String getShiftListApi = '/api/Mobile/Requests/GetShiftRequestList';
  static const String getShiftDetailApi = '/api/Mobile/Requests/GetDefaultShiftRequestDetail';
  static const String getLeaveBalance = '/api/Mobile/LeavesBalance/GetEmployeeLeaveBalance';
  static const String mobileDeviceAddUpdate = '/api/Mobile/Device/AddOrUpdate';

  static const String fcmTokenUpdate = '/api/Mobile/Requests/UpdateDeviceToken';
  static const String postNotificationSettings = '/api/Mobile/Requests/UpdateAllowOrDisAllowNotification';
  static const String getNotificationSettings = '/api/Mobile/Requests/GetNotificationSetting';

  static const String getAllRequestDetailApi = '/api/Mobile/Requests/GetALLRequestDetails';

  // static const String t = '';
  // static const String t = '';
  // static const String t = '';
  // static const String t = '';
  // static const String t = '';
  // static const String t = '';
  // static const String t = '';
  // static const String t = '';
  // static const String t = '';
  // static const String t = '';
  // static const String t = '';
  // static const String t = '';
  // static const String t = '';
  // static const String t = '';
  // static const String t = '';
  // static const String t = '';
  // static const String t = '';
  // static const String t = '';
  // static const String t = '';
  // static const String t = '';
  // static const String t = '';
  // static const String t = '';
  // static const String t = '';
  // static const String t = '';
  // static const String t = '';

}
