name: 'Build & Release'
on:
  pull_request:
    branches:
      - main
      - test
  push:
    branches:
      - main
      - test
jobs:   # Telling what jobs we need to happen
  version:
    name: Create version number
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v0.9.7
        with:
          versionSpec: "5.x"
      - name: Use GitVersion
        id: gitversion
        uses: gittools/actions/gitversion/execute@v0.9.7
      - name: Create version.txt with nuGetVersion
        run: echo ${{ steps.gitversion.outputs.nuGetVersion  }} > version.txt
      - name: Upload version.txt
        uses: actions/upload-artifact@v2
        with:
          name: gitversion
          path: version.txt
  build:      # Specify the building name and machine
    name: Build & Release  # you can name the build whatever you want
      # device we want our code to run on ( macos - ubuntu - windows )
    # here we selected macos-latest to be able to get ios build
    runs-on: macos-latest
    steps:
      - name: CheckOut Repo
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3.12.0
        with:
          java-version: '11'
          cache: 'gradle'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.16.1' # Specify the Flutter version required for your project
          channel: 'stable'
          cache: true

      - name: Install Dependencies
        run: flutter pub get

      #5 run test
      - name: Test flutter app
        run: flutter test

      - name: Start release build
        run: flutter build appbundle --flavor peopleqlik -t lib/commonApps/peopleqlik.dart


